services:
  tail-web:
    build: .
    container_name: fakessh-tail
    ports:
      - "127.0.0.1:7681:7681"
    volumes:
      - /var/log/fakessh.log:/var/log/0.log:ro
    environment:
      - ANONYMIZE_MODE=partial
      - FILTER_WORDS=LeasewebSG
      - LWS_LOG_LEVEL=1
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    restart: unless-stopped
